import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)
import java.lang.Object;

/**
 * Write a description of class Nivel here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class Nivel extends Actor
{
    /**
     * Act - do whatever the Nivel wants to do. This method is called whenever
     * the 'Act' or 'Run' button gets pressed in the environment.
     */
    public void act() 
    {
        
    }  
    
    public void finali()
    {
        WombatWorld mundo = (WombatWorld) getWorld();
                Contador counter = mundo.cPuntos(); 
                counter.setLocation( 10, 4);
                counter = mundo.cVidas(); 
                counter.setLocation(10, 6);
                counter = mundo.cMuniciones(); 
                counter.setLocation(10, 8);
                counter = mundo.cNivel(); 
                counter.setLocation(10, 10);
        getWorld().setBackground("fin.jpg");
    }
    public void n2()
    {
        World myWorld = getWorld();
        /*Jugador jugador = new Jugador();
myWorld.addObject(jugador, 7, 5);*/

        Recarga r= new Recarga();
        myWorld.addObject(r,9,2);
        Recarga r2= new Recarga();
        myWorld.addObject(r2,9,9);
        bloque obstaculo = new bloque();
        myWorld.addObject(obstaculo, 3, 3);
        bloque obstaculo2 = new bloque();
        Vida vid = new Vida();
        myWorld.addObject(vid,4,11);
myWorld.addObject(obstaculo2, 3, 5);
        bloque obstaculo3 = new bloque();
myWorld.addObject(obstaculo3, 3, 7);
        bloque obstaculo4 = new bloque();
myWorld.addObject(obstaculo4, 3, 9);
        bloque obstaculo5 = new bloque();
myWorld.addObject(obstaculo5, 5, 9);
        bloque obstaculo6 = new bloque();
myWorld.addObject(obstaculo6, 8, 9);
        bloque obstaculo7 = new bloque();
myWorld.addObject(obstaculo7, 7, 3);
        bloque obstaculo8 = new bloque();
myWorld.addObject(obstaculo8, 10, 3);
        bloque obstaculo9 = new bloque();
myWorld.addObject(obstaculo9, 10, 5);
        bloque obstaculo10 = new bloque();
myWorld.addObject(obstaculo10, 10, 7);
        bloque obstaculo11 = new bloque();
myWorld.addObject(obstaculo11, 6, 3);
        bloque obstaculo12 = new bloque();
myWorld.addObject(obstaculo12, 5, 3);
        bloque obstaculo13 = new bloque();
myWorld.addObject(obstaculo13, 3, 6);
        bloque obstaculo14 = new bloque();
myWorld.addObject(obstaculo14, 3, 8);
        bloque obstaculo15 = new bloque();
myWorld.addObject(obstaculo15, 2, 9);
        bloque obstaculo16 = new bloque();
myWorld.addObject(obstaculo16, 10, 8);
        bloque obstaculo17 = new bloque();
myWorld.addObject(obstaculo17, 10, 9);
        bloque obstaculo18 = new bloque();
myWorld.addObject(obstaculo18, 9, 3);
        bloque obstaculo19 = new bloque();
myWorld.addObject(obstaculo19, 12, 3);
        bloque obstaculo20 = new bloque();
myWorld.addObject(obstaculo20, 13, 3);
        Llave llave = new Llave();
myWorld.addObject(llave, 14, 6);
        Enemigo enemigo = new Enemigo();
myWorld.addObject(enemigo, 11, 3);
        Enemigo enemigo2 = new Enemigo();
myWorld.addObject(enemigo2, 6, 2);
        Fantasma fantasma = new Fantasma();
myWorld.addObject(fantasma, 6, 9);
        Fantasma fantasma2 = new Fantasma();
myWorld.addObject(fantasma2, 2, 11);
        obstaculo obstaculo21 = new obstaculo();
myWorld.addObject(obstaculo21, 10, 6);
        fantasma.setLocation(4, 11);
        myWorld.removeObject(obstaculo15);
        bloque obstaculo22 = new bloque();
myWorld.addObject(obstaculo22, 4, 9);
        bloque obstaculo23 = new bloque();
myWorld.addObject(obstaculo23, 6, 9);
        bloque obstaculo24 = new bloque();
myWorld.addObject(obstaculo24, 7, 9);
        bloque obstaculo25 = new bloque();
myWorld.addObject(obstaculo25, 9, 9);
        bloque obstaculo26 = new bloque();
myWorld.addObject(obstaculo26, 11, 9);
        bloque obstaculo27 = new bloque();
myWorld.addObject(obstaculo27, 13, 9);
        bloque obstaculo28 = new bloque();
myWorld.addObject(obstaculo28, 12, 9);
        bloque obstaculo29 = new bloque();
myWorld.addObject(obstaculo29, 14, 9);
        bloque obstaculo30 = new bloque();
myWorld.addObject(obstaculo30, 14, 3);
        bloque obstaculo31 = new bloque();
myWorld.addObject(obstaculo31, 15, 3);
        bloque obstaculo32 = new bloque();
myWorld.addObject(obstaculo32, 16, 4);
        bloque obstaculo33 = new bloque();
myWorld.addObject(obstaculo33, 16, 3);
        bloque obstaculo34 = new bloque();
myWorld.addObject(obstaculo34, 16, 5);
        bloque obstaculo35 = new bloque();
myWorld.addObject(obstaculo35, 16, 6);
        bloque obstaculo36 = new bloque();
myWorld.addObject(obstaculo36, 16, 7);
        bloque obstaculo37 = new bloque();
myWorld.addObject(obstaculo37, 16, 8);
        bloque obstaculo38 = new bloque();
myWorld.addObject(obstaculo38, 16, 9);
        bloque obstaculo39 = new bloque();
myWorld.addObject(obstaculo39, 15, 9);
        bloque obstaculo40 = new bloque();
myWorld.addObject(obstaculo40, 3, 4);
        bloque obstaculo41 = new bloque();
myWorld.addObject(obstaculo41, 4, 3);
        bloque obstaculo42 = new bloque();
myWorld.addObject(obstaculo42, 8, 3);
        enemigo.setLocation(12, 6);
        bloque obstaculo43 = new bloque();
myWorld.addObject(obstaculo43, 11, 3);
        bloque obstaculo44 = new bloque();
myWorld.addObject(obstaculo44, 10, 4);
        myWorld.removeObject(obstaculo5);
        myWorld.removeObject(obstaculo24);
        myWorld.removeObject(obstaculo28);
        myWorld.removeObject(obstaculo29);
        bloque obstaculo45 = new bloque();
myWorld.addObject(obstaculo45, 3, 10);
        bloque obstaculo46 = new bloque();
myWorld.addObject(obstaculo46, 3, 11);
        fantasma.setLocation(1, 9);
        myWorld.removeObject(fantasma2);
        myWorld.removeObject(fantasma);
        bloque obstaculo47 = new bloque();
myWorld.addObject(obstaculo47, 4, 11);
        bloque obstaculo48 = new bloque();
myWorld.addObject(obstaculo48, 5, 11);
        bloque obstaculo49 = new bloque();
myWorld.addObject(obstaculo49, 6, 11);
        bloque obstaculo50 = new bloque();
myWorld.addObject(obstaculo50, 7, 11);
        bloque obstaculo51 = new bloque();
myWorld.addObject(obstaculo51, 8, 11);
        bloque obstaculo52 = new bloque();
myWorld.addObject(obstaculo52, 9, 11);
        bloque obstaculo53 = new bloque();
myWorld.addObject(obstaculo53, 10, 11);
        bloque obstaculo54 = new bloque();
myWorld.addObject(obstaculo54, 11, 11);
        bloque obstaculo55 = new bloque();
myWorld.addObject(obstaculo55, 12, 11);
        bloque obstaculo56 = new bloque();
myWorld.addObject(obstaculo56, 13, 11);
        bloque obstaculo57 = new bloque();
myWorld.addObject(obstaculo57, 14, 11);
        bloque obstaculo58 = new bloque();
myWorld.addObject(obstaculo58, 15, 11);
        bloque obstaculo59 = new bloque();
myWorld.addObject(obstaculo59, 16, 11);
        bloque obstaculo60 = new bloque();
myWorld.addObject(obstaculo60, 16, 10);
        myWorld.removeObject(obstaculo25);
        myWorld.removeObject(obstaculo17);
        myWorld.removeObject(obstaculo26);
        obstaculo22.setLocation(4, 8);
        obstaculo23.setLocation(6, 8);
        obstaculo6.setLocation(8, 8);
        obstaculo27.setLocation(13, 8);
        obstaculo39.setLocation(15, 8);
        llave.setLocation(4, 10);
        meta meta = new meta();
myWorld.addObject(meta, 15, 4);
        obstaculo obstaculo61 = new obstaculo();
myWorld.addObject(obstaculo61, 5, 8);
        obstaculo obstaculo62 = new obstaculo();
myWorld.addObject(obstaculo62, 5, 9);
        obstaculo obstaculo63 = new obstaculo();
myWorld.addObject(obstaculo63, 4, 9);
        obstaculo obstaculo64 = new obstaculo();
myWorld.addObject(obstaculo64, 5, 10);
        obstaculo obstaculo65 = new obstaculo();
myWorld.addObject(obstaculo65, 6, 10);
        obstaculo obstaculo66 = new obstaculo();
myWorld.addObject(obstaculo66, 6, 9);
        obstaculo obstaculo67 = new obstaculo();
myWorld.addObject(obstaculo67, 7, 9);
        obstaculo obstaculo68 = new obstaculo();
myWorld.addObject(obstaculo68, 7, 10);
        obstaculo obstaculo69 = new obstaculo();
myWorld.addObject(obstaculo69, 7, 8);
        obstaculo obstaculo70 = new obstaculo();
myWorld.addObject(obstaculo70, 7, 8);
        obstaculo obstaculo71 = new obstaculo();
myWorld.addObject(obstaculo71, 6, 7);
        obstaculo obstaculo72 = new obstaculo();
myWorld.addObject(obstaculo72, 8, 7);
        obstaculo obstaculo73 = new obstaculo();
myWorld.addObject(obstaculo73, 7, 7);
        obstaculo obstaculo74 = new obstaculo();
myWorld.addObject(obstaculo74, 5, 7);
        obstaculo obstaculo75 = new obstaculo();
myWorld.addObject(obstaculo75, 5, 7);
        obstaculo obstaculo76 = new obstaculo();
myWorld.addObject(obstaculo76, 4, 7);
        obstaculo obstaculo77 = new obstaculo();
myWorld.addObject(obstaculo77, 9, 7);
        obstaculo obstaculo78 = new obstaculo();
myWorld.addObject(obstaculo78, 9, 8);
        obstaculo obstaculo79 = new obstaculo();
myWorld.addObject(obstaculo79, 9, 9);
        obstaculo obstaculo80 = new obstaculo();
myWorld.addObject(obstaculo80, 8, 9);
        obstaculo obstaculo81 = new obstaculo();
myWorld.addObject(obstaculo81, 8, 10);
        obstaculo obstaculo82 = new obstaculo();
myWorld.addObject(obstaculo82, 9, 10);
        myWorld.removeObject(obstaculo61);
        myWorld.removeObject(obstaculo66);
        //jugador.setLocation(4, 4);
        obstaculo obstaculo83 = new obstaculo();
myWorld.addObject(obstaculo83, 9, 6);
        obstaculo obstaculo84 = new obstaculo();
myWorld.addObject(obstaculo84, 9, 5);
        obstaculo83.setLocation(8, 6);
        obstaculo84.setLocation(4, 6);
        obstaculo obstaculo85 = new obstaculo();
myWorld.addObject(obstaculo85, 5, 6);
        enemigo2.setLocation(7, 6);
        obstaculo obstaculo86 = new obstaculo();
myWorld.addObject(obstaculo86, 6, 6);
        obstaculo obstaculo87 = new obstaculo();
myWorld.addObject(obstaculo87, 6, 5);
        obstaculo obstaculo88 = new obstaculo();
myWorld.addObject(obstaculo88, 6, 4);
        obstaculo obstaculo89 = new obstaculo();
myWorld.addObject(obstaculo89, 7, 4);
        obstaculo obstaculo90 = new obstaculo();
myWorld.addObject(obstaculo90, 7, 5);
        obstaculo obstaculo91 = new obstaculo();
myWorld.addObject(obstaculo91, 8, 5);
        obstaculo obstaculo92 = new obstaculo();
myWorld.addObject(obstaculo92, 9, 4);
        obstaculo obstaculo93 = new obstaculo();
myWorld.addObject(obstaculo93, 8, 4);
        obstaculo obstaculo94 = new obstaculo();
myWorld.addObject(obstaculo94, 9, 5);
        obstaculo obstaculo95 = new obstaculo();
myWorld.addObject(obstaculo95, 11, 8);
        obstaculo obstaculo96 = new obstaculo();
myWorld.addObject(obstaculo96, 12, 8);
        obstaculo obstaculo97 = new obstaculo();
myWorld.addObject(obstaculo97, 14, 8);
        enemigo.setLocation(11, 10);
        obstaculo obstaculo98 = new obstaculo();
myWorld.addObject(obstaculo98, 13, 4);
        obstaculo obstaculo99 = new obstaculo();
myWorld.addObject(obstaculo99, 13, 5);
        obstaculo obstaculo100 = new obstaculo();
myWorld.addObject(obstaculo100, 13, 6);
        obstaculo obstaculo101 = new obstaculo();
myWorld.addObject(obstaculo101, 13, 7);
        obstaculo obstaculo102 = new obstaculo();
myWorld.addObject(obstaculo102, 15, 7);
        obstaculo obstaculo103 = new obstaculo();
myWorld.addObject(obstaculo103, 14, 7);
        obstaculo obstaculo104 = new obstaculo();
myWorld.addObject(obstaculo104, 14, 6);
        obstaculo obstaculo105 = new obstaculo();
myWorld.addObject(obstaculo105, 15, 6);
        obstaculo obstaculo106 = new obstaculo();
myWorld.addObject(obstaculo106, 14, 5);
        obstaculo106.setLocation(12, 4);
        Enemigo enemigo3 = new Enemigo();
myWorld.addObject(enemigo3, 12, 5);
        obstaculo obstaculo107 = new obstaculo();
myWorld.addObject(obstaculo107, 11, 5);
        obstaculo obstaculo108 = new obstaculo();
myWorld.addObject(obstaculo108, 11, 6);
        obstaculo obstaculo109 = new obstaculo();
myWorld.addObject(obstaculo109, 11, 7);
        obstaculo obstaculo110 = new obstaculo();
myWorld.addObject(obstaculo110, 13, 7);
        obstaculo obstaculo111 = new obstaculo();
myWorld.addObject(obstaculo111, 12, 7);
        obstaculo obstaculo112 = new obstaculo();
myWorld.addObject(obstaculo112, 12, 6);
        obstaculo103.setLocation(15, 10);
        obstaculo97.setLocation(15, 9);
        obstaculo111.setLocation(12, 10);
        obstaculo80.setLocation(14, 10);
        obstaculo108.setLocation(14, 9);
        obstaculo95.setLocation(11, 9);
        obstaculo79.setLocation(10, 9);
        obstaculo108.setLocation(13, 9);
        obstaculo102.setLocation(14, 7);
        obstaculo47.setLocation(3, 12);
        obstaculo48.setLocation(4, 12);
        obstaculo49.setLocation(5, 12);
        obstaculo50.setLocation(6, 12);
        obstaculo51.setLocation(7, 12);
        obstaculo52.setLocation(8, 12);
        obstaculo58.setLocation(16, 12);
        obstaculo57.setLocation(15, 12);
        obstaculo56.setLocation(14, 12);
        obstaculo55.setLocation(13, 12);
        obstaculo54.setLocation(12, 12);
        obstaculo53.setLocation(11, 12);
        obstaculo41.setLocation(3, 2);
        obstaculo12.setLocation(4, 2);
        obstaculo11.setLocation(5, 2);
        obstaculo7.setLocation(6, 2);
        obstaculo42.setLocation(7, 2);
        obstaculo18.setLocation(8, 2);
        obstaculo8.setLocation(9, 2);
        obstaculo43.setLocation(10, 2);
        obstaculo12.setLocation(3, 1);
        obstaculo11.setLocation(4, 1);
        obstaculo7.setLocation(5, 1);
        obstaculo42.setLocation(6, 1);
        obstaculo18.setLocation(7, 1);
        obstaculo8.setLocation(8, 1);
        obstaculo43.setLocation(9, 1);
        obstaculo19.setLocation(10, 1);
        obstaculo20.setLocation(16, 3);
        obstaculo31.setLocation(16, 2);
        obstaculo30.setLocation(15, 2);
        obstaculo30.setLocation(16, 1);
        obstaculo33.setLocation(15, 1);
        bloque obstaculo113 = new bloque();
myWorld.addObject(obstaculo113, 14, 1);
        bloque obstaculo114 = new bloque();
myWorld.addObject(obstaculo114, 13, 1);
        bloque obstaculo115 = new bloque();
myWorld.addObject(obstaculo115, 11, 1);
        bloque obstaculo116 = new bloque();
myWorld.addObject(obstaculo116, 12, 1);
        bloque obstaculo117 = new bloque();
myWorld.addObject(obstaculo117, 9, 12);
        bloque obstaculo118 = new bloque();
myWorld.addObject(obstaculo118, 10, 12);
        //jugador.setLocation(4, 1);
        obstaculo12.setLocation(2, 1);
        obstaculo41.setLocation(2, 2);
        obstaculo11.setLocation(3, 0);
        //jugador.setLocation(4, 2);
        obstaculo11.setLocation(4, 1);
        obstaculo12.setLocation(3, 1);
        obstaculo41.setLocation(3, 2);
        obstaculo88.setLocation(6, 2);
        obstaculo87.setLocation(6, 3);
        obstaculo84.setLocation(4, 4);
        obstaculo85.setLocation(5, 5);
        obstaculo85.setLocation(5, 4);
        obstaculo86.setLocation(6, 4);
        obstaculo44.setLocation(9, 2);
        llave.setLocation(15, 11);
        meta.setLocation(10, 2);
        bloque obstaculo119 = new bloque();
myWorld.addObject(obstaculo119, 9, 3);
        bloque obstaculo120 = new bloque();
myWorld.addObject(obstaculo120, 5, 8);
        obstaculo75.setLocation(5, 5);
        obstaculo74.setLocation(5, 6);
        obstaculo120.setLocation(5, 8);
        obstaculo74.setLocation(5, 7);
        obstaculo119.setLocation(7, 3);
        obstaculo44.setLocation(9, 3);
        bloque obstaculo121 = new bloque();
myWorld.addObject(obstaculo121, 8, 3);
        bloque obstaculo122 = new bloque();
myWorld.addObject(obstaculo122, 8, 2);
        meta.setLocation(9, 2);
        obstaculo obstaculo123 = new obstaculo();
myWorld.addObject(obstaculo123, 13, 10);
        obstaculo obstaculo124 = new obstaculo();
myWorld.addObject(obstaculo124, 13, 11);
        obstaculo obstaculo125 = new obstaculo();
myWorld.addObject(obstaculo125, 14, 11);
        obstaculo80.setLocation(14, 8);
        enemigo.setLocation(14, 9);
        obstaculo obstaculo126 = new obstaculo();
myWorld.addObject(obstaculo126, 11, 10);
        obstaculo obstaculo127 = new obstaculo();
myWorld.addObject(obstaculo127, 10, 10);
        obstaculo obstaculo128 = new obstaculo();
myWorld.addObject(obstaculo128, 12, 11);
        obstaculo obstaculo129 = new obstaculo();
myWorld.addObject(obstaculo129, 11, 11);
        obstaculo obstaculo130 = new obstaculo();
myWorld.addObject(obstaculo130, 10, 11);
        obstaculo obstaculo131 = new obstaculo();
myWorld.addObject(obstaculo131, 9, 11);
        obstaculo obstaculo132 = new obstaculo();
myWorld.addObject(obstaculo132, 8, 11);
        obstaculo obstaculo133 = new obstaculo();
myWorld.addObject(obstaculo133, 7, 11);
        obstaculo obstaculo134 = new obstaculo();
myWorld.addObject(obstaculo134, 6, 11);
        obstaculo obstaculo135 = new obstaculo();
myWorld.addObject(obstaculo135, 5, 11);
        obstaculo obstaculo136 = new obstaculo();
myWorld.addObject(obstaculo136, 4, 11);
        obstaculo obstaculo137 = new obstaculo();
myWorld.addObject(obstaculo137, 4, 11);
        obstaculo obstaculo138 = new obstaculo();
myWorld.addObject(obstaculo138, 4, 10);
        obstaculo92.setLocation(10, 2);
        obstaculo93.setLocation(9, 4);
        Fantasma fantasma3 = new Fantasma();
myWorld.addObject(fantasma3, 9, 9);
        obstaculo82.setLocation(14, 5);
        obstaculo75.setLocation(5, 6);
        obstaculo90.setLocation(5, 5);
        obstaculo21.setLocation(9, 6);
        bloque obstaculo139 = new bloque();
myWorld.addObject(obstaculo139, 10, 6);
        bloque obstaculo140 = new bloque();
myWorld.addObject(obstaculo140, 10, 4);
        bloque obstaculo141 = new bloque();
myWorld.addObject(obstaculo141, 10, 3);
        obstaculo78.setLocation(8, 9);
        obstaculo6.setLocation(9, 8);
        obstaculo23.setLocation(8, 8);
        obstaculo70.setLocation(6, 9);
        obstaculo120.setLocation(6, 8);
        obstaculo119.setLocation(5, 8);
        obstaculo139.setLocation(9, 10);
        obstaculo obstaculo142 = new obstaculo();
myWorld.addObject(obstaculo142, 13, 3);
        obstaculo obstaculo143 = new obstaculo();
myWorld.addObject(obstaculo143, 13, 2);
        Enemigo enemigo4 = new Enemigo();
myWorld.addObject(enemigo4, 15, 2);
        bloque obstaculo144 = new bloque();
myWorld.addObject(obstaculo144, 10, 6);
        obstaculo110.setLocation(12, 7);
        obstaculo142.setLocation(12, 3);
        obstaculo143.setLocation(12, 2);
        obstaculo112.setLocation(11, 6);
        obstaculo100.setLocation(12, 6);
        bloque obstaculo145 = new bloque();
myWorld.addObject(obstaculo145, 13, 6);
        obstaculo101.setLocation(15, 7);
        bloque obstaculo146 = new bloque();
myWorld.addObject(obstaculo146, 13, 7);
        obstaculo99.setLocation(15, 5);
        obstaculo98.setLocation(15, 4);
        bloque obstaculo147 = new bloque();
myWorld.addObject(obstaculo147, 13, 5);
        bloque obstaculo148 = new bloque();
myWorld.addObject(obstaculo148, 13, 4);
        bloque obstaculo149 = new bloque();
myWorld.addObject(obstaculo149, 13, 4);
        bloque obstaculo150 = new bloque();
myWorld.addObject(obstaculo150, 13, 3);
        obstaculo108.setLocation(12, 9);
        bloque obstaculo151 = new bloque();
myWorld.addObject(obstaculo151, 13, 9);
        obstaculo123.setLocation(14, 10);
        obstaculo111.setLocation(13, 10);
        obstaculo108.setLocation(12, 10);
        obstaculo95.setLocation(12, 9);
        obstaculo96.setLocation(11, 9);
        bloque obstaculo152 = new bloque();
myWorld.addObject(obstaculo152, 12, 8);
        bloque obstaculo153 = new bloque();
myWorld.addObject(obstaculo153, 11, 8);
        meta.setLocation(11, 3);
        obstaculo110.setLocation(9, 2);
        meta.setLocation(12, 7);
        obstaculo111.setLocation(14, 4);
        obstaculo obstaculo154 = new obstaculo();
myWorld.addObject(obstaculo154, 7, 3);
        obstaculo obstaculo155 = new obstaculo();
myWorld.addObject(obstaculo155, 7, 2);
    }
    
    public void n3()
    {
        World myWorld = getWorld();
        
        Vida v = new Vida();
        myWorld.addObject(v,14,9);
        Recarga r= new Recarga();
        myWorld.addObject(r,16,2);
        Recarga r2= new Recarga();
        myWorld.addObject(r2,7,5);
        /*Jugador jugador = new Jugador();
myWorld.addObject(jugador, 7, 5);*/
        bloque obstaculo = new bloque();
myWorld.addObject(obstaculo, 3, 3);
        bloque obstaculo2 = new bloque();
myWorld.addObject(obstaculo2, 3, 5);
        bloque obstaculo3 = new bloque();
myWorld.addObject(obstaculo3, 3, 7);
        bloque obstaculo4 = new bloque();
myWorld.addObject(obstaculo4, 3, 9);
        bloque obstaculo5 = new bloque();
myWorld.addObject(obstaculo5, 5, 9);
        bloque obstaculo6 = new bloque();
myWorld.addObject(obstaculo6, 8, 9);
        bloque obstaculo7 = new bloque();
myWorld.addObject(obstaculo7, 7, 3);
        bloque obstaculo8 = new bloque();
myWorld.addObject(obstaculo8, 10, 3);
        bloque obstaculo9 = new bloque();
myWorld.addObject(obstaculo9, 10, 5);
        bloque obstaculo10 = new bloque();
myWorld.addObject(obstaculo10, 10, 7);
        bloque obstaculo11 = new bloque();
myWorld.addObject(obstaculo11, 6, 3);
        bloque obstaculo12 = new bloque();
myWorld.addObject(obstaculo12, 5, 3);
        bloque obstaculo13 = new bloque();
myWorld.addObject(obstaculo13, 3, 6);
        bloque obstaculo14 = new bloque();
myWorld.addObject(obstaculo14, 3, 8);
        bloque obstaculo15 = new bloque();
myWorld.addObject(obstaculo15, 2, 9);
        bloque obstaculo16 = new bloque();
myWorld.addObject(obstaculo16, 10, 8);
        bloque obstaculo17 = new bloque();
myWorld.addObject(obstaculo17, 10, 9);
        bloque obstaculo18 = new bloque();
myWorld.addObject(obstaculo18, 9, 3);
        bloque obstaculo19 = new bloque();
myWorld.addObject(obstaculo19, 12, 3);
        bloque obstaculo20 = new bloque();
myWorld.addObject(obstaculo20, 13, 3);
        Llave llave = new Llave();
myWorld.addObject(llave, 14, 6);
        Enemigo enemigo = new Enemigo();
myWorld.addObject(enemigo, 11, 3);
        Enemigo enemigo2 = new Enemigo();
myWorld.addObject(enemigo2, 6, 2);
        Fantasma fantasma = new Fantasma();
myWorld.addObject(fantasma, 6, 9);
        Fantasma fantasma2 = new Fantasma();
myWorld.addObject(fantasma2, 2, 11);
        obstaculo obstaculo21 = new obstaculo();
myWorld.addObject(obstaculo21, 10, 6);
        fantasma.setLocation(4, 11);
        myWorld.removeObject(obstaculo15);
        bloque obstaculo22 = new bloque();
myWorld.addObject(obstaculo22, 4, 9);
        bloque obstaculo23 = new bloque();
myWorld.addObject(obstaculo23, 6, 9);
        bloque obstaculo24 = new bloque();
myWorld.addObject(obstaculo24, 7, 9);
        bloque obstaculo25 = new bloque();
myWorld.addObject(obstaculo25, 9, 9);
        bloque obstaculo26 = new bloque();
myWorld.addObject(obstaculo26, 11, 9);
        bloque obstaculo27 = new bloque();
myWorld.addObject(obstaculo27, 13, 9);
        bloque obstaculo28 = new bloque();
myWorld.addObject(obstaculo28, 12, 9);
        bloque obstaculo29 = new bloque();
myWorld.addObject(obstaculo29, 14, 9);
        bloque obstaculo30 = new bloque();
myWorld.addObject(obstaculo30, 14, 3);
        bloque obstaculo31 = new bloque();
myWorld.addObject(obstaculo31, 15, 3);
        bloque obstaculo32 = new bloque();
myWorld.addObject(obstaculo32, 16, 4);
        bloque obstaculo33 = new bloque();
myWorld.addObject(obstaculo33, 16, 3);
        bloque obstaculo34 = new bloque();
myWorld.addObject(obstaculo34, 16, 5);
        bloque obstaculo35 = new bloque();
myWorld.addObject(obstaculo35, 16, 6);
        bloque obstaculo36 = new bloque();
myWorld.addObject(obstaculo36, 16, 7);
        bloque obstaculo37 = new bloque();
myWorld.addObject(obstaculo37, 16, 8);
        bloque obstaculo38 = new bloque();
myWorld.addObject(obstaculo38, 16, 9);
        bloque obstaculo39 = new bloque();
myWorld.addObject(obstaculo39, 15, 9);
        bloque obstaculo40 = new bloque();
myWorld.addObject(obstaculo40, 3, 4);
        bloque obstaculo41 = new bloque();
myWorld.addObject(obstaculo41, 4, 3);
        bloque obstaculo42 = new bloque();
myWorld.addObject(obstaculo42, 8, 3);
        enemigo.setLocation(12, 6);
        bloque obstaculo43 = new bloque();
myWorld.addObject(obstaculo43, 11, 3);
        bloque obstaculo44 = new bloque();
myWorld.addObject(obstaculo44, 10, 4);
        myWorld.removeObject(obstaculo5);
        myWorld.removeObject(obstaculo24);
        myWorld.removeObject(obstaculo28);
        myWorld.removeObject(obstaculo29);
        bloque obstaculo45 = new bloque();
myWorld.addObject(obstaculo45, 3, 10);
        bloque obstaculo46 = new bloque();
myWorld.addObject(obstaculo46, 3, 11);
        fantasma.setLocation(1, 9);
        myWorld.removeObject(fantasma2);
        myWorld.removeObject(fantasma);
        bloque obstaculo47 = new bloque();
myWorld.addObject(obstaculo47, 4, 11);
        bloque obstaculo48 = new bloque();
myWorld.addObject(obstaculo48, 5, 11);
        bloque obstaculo49 = new bloque();
myWorld.addObject(obstaculo49, 6, 11);
        bloque obstaculo50 = new bloque();
myWorld.addObject(obstaculo50, 7, 11);
        bloque obstaculo51 = new bloque();
myWorld.addObject(obstaculo51, 8, 11);
        bloque obstaculo52 = new bloque();
myWorld.addObject(obstaculo52, 9, 11);
        bloque obstaculo53 = new bloque();
myWorld.addObject(obstaculo53, 10, 11);
        bloque obstaculo54 = new bloque();
myWorld.addObject(obstaculo54, 11, 11);
        bloque obstaculo55 = new bloque();
myWorld.addObject(obstaculo55, 12, 11);
        bloque obstaculo56 = new bloque();
myWorld.addObject(obstaculo56, 13, 11);
        bloque obstaculo57 = new bloque();
myWorld.addObject(obstaculo57, 14, 11);
        bloque obstaculo58 = new bloque();
myWorld.addObject(obstaculo58, 15, 11);
        bloque obstaculo59 = new bloque();
myWorld.addObject(obstaculo59, 16, 11);
        bloque obstaculo60 = new bloque();
myWorld.addObject(obstaculo60, 16, 10);
        myWorld.removeObject(obstaculo25);
        myWorld.removeObject(obstaculo17);
        myWorld.removeObject(obstaculo26);
        obstaculo22.setLocation(4, 8);
        obstaculo23.setLocation(6, 8);
        obstaculo6.setLocation(8, 8);
        obstaculo27.setLocation(13, 8);
        obstaculo39.setLocation(15, 8);
        llave.setLocation(4, 10);
        meta meta = new meta();
myWorld.addObject(meta, 15, 4);
        obstaculo obstaculo61 = new obstaculo();
myWorld.addObject(obstaculo61, 5, 8);
        obstaculo obstaculo62 = new obstaculo();
myWorld.addObject(obstaculo62, 5, 9);
        obstaculo obstaculo63 = new obstaculo();
myWorld.addObject(obstaculo63, 4, 9);
        obstaculo obstaculo64 = new obstaculo();
myWorld.addObject(obstaculo64, 5, 10);
        obstaculo obstaculo65 = new obstaculo();
myWorld.addObject(obstaculo65, 6, 10);
        obstaculo obstaculo66 = new obstaculo();
myWorld.addObject(obstaculo66, 6, 9);
        obstaculo obstaculo67 = new obstaculo();
myWorld.addObject(obstaculo67, 7, 9);
        obstaculo obstaculo68 = new obstaculo();
myWorld.addObject(obstaculo68, 7, 10);
        obstaculo obstaculo69 = new obstaculo();
myWorld.addObject(obstaculo69, 7, 8);
        obstaculo obstaculo70 = new obstaculo();
myWorld.addObject(obstaculo70, 7, 8);
        obstaculo obstaculo71 = new obstaculo();
myWorld.addObject(obstaculo71, 6, 7);
        obstaculo obstaculo72 = new obstaculo();
myWorld.addObject(obstaculo72, 8, 7);
        obstaculo obstaculo73 = new obstaculo();
myWorld.addObject(obstaculo73, 7, 7);
        obstaculo obstaculo74 = new obstaculo();
myWorld.addObject(obstaculo74, 5, 7);
        obstaculo obstaculo75 = new obstaculo();
myWorld.addObject(obstaculo75, 5, 7);
        obstaculo obstaculo76 = new obstaculo();
myWorld.addObject(obstaculo76, 4, 7);
        obstaculo obstaculo77 = new obstaculo();
myWorld.addObject(obstaculo77, 9, 7);
        obstaculo obstaculo78 = new obstaculo();
myWorld.addObject(obstaculo78, 9, 8);
        obstaculo obstaculo79 = new obstaculo();
myWorld.addObject(obstaculo79, 9, 9);
        obstaculo obstaculo80 = new obstaculo();
myWorld.addObject(obstaculo80, 8, 9);
        obstaculo obstaculo81 = new obstaculo();
myWorld.addObject(obstaculo81, 8, 10);
        obstaculo obstaculo82 = new obstaculo();
myWorld.addObject(obstaculo82, 9, 10);
        myWorld.removeObject(obstaculo61);
        myWorld.removeObject(obstaculo66);
        //jugador.setLocation(4, 4);
        obstaculo obstaculo83 = new obstaculo();
myWorld.addObject(obstaculo83, 9, 6);
        obstaculo obstaculo84 = new obstaculo();
myWorld.addObject(obstaculo84, 9, 5);
        obstaculo83.setLocation(8, 6);
        obstaculo84.setLocation(4, 6);
        obstaculo obstaculo85 = new obstaculo();
myWorld.addObject(obstaculo85, 5, 6);
        enemigo2.setLocation(7, 6);
        obstaculo obstaculo86 = new obstaculo();
myWorld.addObject(obstaculo86, 6, 6);
        obstaculo obstaculo87 = new obstaculo();
myWorld.addObject(obstaculo87, 6, 5);
        obstaculo obstaculo88 = new obstaculo();
myWorld.addObject(obstaculo88, 6, 4);
        obstaculo obstaculo89 = new obstaculo();
myWorld.addObject(obstaculo89, 7, 4);
        obstaculo obstaculo90 = new obstaculo();
myWorld.addObject(obstaculo90, 7, 5);
        obstaculo obstaculo91 = new obstaculo();
myWorld.addObject(obstaculo91, 8, 5);
        obstaculo obstaculo92 = new obstaculo();
myWorld.addObject(obstaculo92, 9, 4);
        obstaculo obstaculo93 = new obstaculo();
myWorld.addObject(obstaculo93, 8, 4);
        obstaculo obstaculo94 = new obstaculo();
myWorld.addObject(obstaculo94, 9, 5);
        obstaculo obstaculo95 = new obstaculo();
myWorld.addObject(obstaculo95, 11, 8);
        obstaculo obstaculo96 = new obstaculo();
myWorld.addObject(obstaculo96, 12, 8);
        obstaculo obstaculo97 = new obstaculo();
myWorld.addObject(obstaculo97, 14, 8);
        enemigo.setLocation(11, 10);
        obstaculo obstaculo98 = new obstaculo();
myWorld.addObject(obstaculo98, 13, 4);
        obstaculo obstaculo99 = new obstaculo();
myWorld.addObject(obstaculo99, 13, 5);
        obstaculo obstaculo100 = new obstaculo();
myWorld.addObject(obstaculo100, 13, 6);
        obstaculo obstaculo101 = new obstaculo();
myWorld.addObject(obstaculo101, 13, 7);
        obstaculo obstaculo102 = new obstaculo();
myWorld.addObject(obstaculo102, 15, 7);
        obstaculo obstaculo103 = new obstaculo();
myWorld.addObject(obstaculo103, 14, 7);
        obstaculo obstaculo104 = new obstaculo();
myWorld.addObject(obstaculo104, 14, 6);
        obstaculo obstaculo105 = new obstaculo();
myWorld.addObject(obstaculo105, 15, 6);
        obstaculo obstaculo106 = new obstaculo();
myWorld.addObject(obstaculo106, 14, 5);
        obstaculo106.setLocation(12, 4);
        Enemigo enemigo3 = new Enemigo();
myWorld.addObject(enemigo3, 12, 5);
        obstaculo obstaculo107 = new obstaculo();
myWorld.addObject(obstaculo107, 11, 5);
        obstaculo obstaculo108 = new obstaculo();
myWorld.addObject(obstaculo108, 11, 6);
        obstaculo obstaculo109 = new obstaculo();
myWorld.addObject(obstaculo109, 11, 7);
        obstaculo obstaculo110 = new obstaculo();
myWorld.addObject(obstaculo110, 13, 7);
        obstaculo obstaculo111 = new obstaculo();
myWorld.addObject(obstaculo111, 12, 7);
        obstaculo obstaculo112 = new obstaculo();
myWorld.addObject(obstaculo112, 12, 6);
        obstaculo103.setLocation(15, 10);
        obstaculo97.setLocation(15, 9);
        obstaculo111.setLocation(12, 10);
        obstaculo80.setLocation(14, 10);
        obstaculo108.setLocation(14, 9);
        obstaculo95.setLocation(11, 9);
        obstaculo79.setLocation(10, 9);
        obstaculo108.setLocation(13, 9);
        obstaculo102.setLocation(14, 7);
        obstaculo47.setLocation(3, 12);
        obstaculo48.setLocation(4, 12);
        obstaculo49.setLocation(5, 12);
        obstaculo50.setLocation(6, 12);
        obstaculo51.setLocation(7, 12);
        obstaculo52.setLocation(8, 12);
        obstaculo58.setLocation(16, 12);
        obstaculo57.setLocation(15, 12);
        obstaculo56.setLocation(14, 12);
        obstaculo55.setLocation(13, 12);
        obstaculo54.setLocation(12, 12);
        obstaculo53.setLocation(11, 12);
        obstaculo41.setLocation(3, 2);
        obstaculo12.setLocation(4, 2);
        obstaculo11.setLocation(5, 2);
        obstaculo7.setLocation(6, 2);
        obstaculo42.setLocation(7, 2);
        obstaculo18.setLocation(8, 2);
        obstaculo8.setLocation(9, 2);
        obstaculo43.setLocation(10, 2);
        obstaculo12.setLocation(3, 1);
        obstaculo11.setLocation(4, 1);
        obstaculo7.setLocation(5, 1);
        obstaculo42.setLocation(6, 1);
        obstaculo18.setLocation(7, 1);
        obstaculo8.setLocation(8, 1);
        obstaculo43.setLocation(9, 1);
        obstaculo19.setLocation(10, 1);
        obstaculo20.setLocation(16, 3);
        obstaculo31.setLocation(16, 2);
        obstaculo30.setLocation(15, 2);
        obstaculo30.setLocation(16, 1);
        obstaculo33.setLocation(15, 1);
        bloque obstaculo113 = new bloque();
myWorld.addObject(obstaculo113, 14, 1);
        bloque obstaculo114 = new bloque();
myWorld.addObject(obstaculo114, 13, 1);
        bloque obstaculo115 = new bloque();
myWorld.addObject(obstaculo115, 11, 1);
        bloque obstaculo116 = new bloque();
myWorld.addObject(obstaculo116, 12, 1);
        bloque obstaculo117 = new bloque();
myWorld.addObject(obstaculo117, 9, 12);
        bloque obstaculo118 = new bloque();
myWorld.addObject(obstaculo118, 10, 12);
        //jugador.setLocation(4, 1);
        obstaculo12.setLocation(2, 1);
        obstaculo41.setLocation(2, 2);
        obstaculo11.setLocation(3, 0);
        //jugador.setLocation(4, 2);
        obstaculo11.setLocation(4, 1);
        obstaculo12.setLocation(3, 1);
        obstaculo41.setLocation(3, 2);
        obstaculo88.setLocation(6, 2);
        obstaculo87.setLocation(6, 3);
        obstaculo84.setLocation(4, 4);
        obstaculo85.setLocation(5, 5);
        obstaculo85.setLocation(5, 4);
        obstaculo86.setLocation(6, 4);
        obstaculo44.setLocation(9, 2);
        llave.setLocation(15, 11);
        meta.setLocation(10, 2);
        bloque obstaculo119 = new bloque();
myWorld.addObject(obstaculo119, 9, 3);
        bloque obstaculo120 = new bloque();
myWorld.addObject(obstaculo120, 5, 8);
        obstaculo75.setLocation(5, 5);
        obstaculo74.setLocation(5, 6);
        obstaculo120.setLocation(5, 8);
        obstaculo74.setLocation(5, 7);
        obstaculo119.setLocation(7, 3);
        obstaculo44.setLocation(9, 3);
        bloque obstaculo121 = new bloque();
myWorld.addObject(obstaculo121, 8, 3);
        bloque obstaculo122 = new bloque();
myWorld.addObject(obstaculo122, 8, 2);
        meta.setLocation(9, 2);
        obstaculo obstaculo123 = new obstaculo();
myWorld.addObject(obstaculo123, 13, 10);
        obstaculo obstaculo124 = new obstaculo();
myWorld.addObject(obstaculo124, 13, 11);
        obstaculo obstaculo125 = new obstaculo();
myWorld.addObject(obstaculo125, 14, 11);
        obstaculo80.setLocation(14, 8);
        enemigo.setLocation(14, 9);
        obstaculo obstaculo126 = new obstaculo();
myWorld.addObject(obstaculo126, 11, 10);
        obstaculo obstaculo127 = new obstaculo();
myWorld.addObject(obstaculo127, 10, 10);
        obstaculo obstaculo128 = new obstaculo();
myWorld.addObject(obstaculo128, 12, 11);
        obstaculo obstaculo129 = new obstaculo();
myWorld.addObject(obstaculo129, 11, 11);
        obstaculo obstaculo130 = new obstaculo();
myWorld.addObject(obstaculo130, 10, 11);
        obstaculo obstaculo131 = new obstaculo();
myWorld.addObject(obstaculo131, 9, 11);
        obstaculo obstaculo132 = new obstaculo();
myWorld.addObject(obstaculo132, 8, 11);
        obstaculo obstaculo133 = new obstaculo();
myWorld.addObject(obstaculo133, 7, 11);
        obstaculo obstaculo134 = new obstaculo();
myWorld.addObject(obstaculo134, 6, 11);
        obstaculo obstaculo135 = new obstaculo();
myWorld.addObject(obstaculo135, 5, 11);
        obstaculo obstaculo136 = new obstaculo();
myWorld.addObject(obstaculo136, 4, 11);
        obstaculo obstaculo137 = new obstaculo();
myWorld.addObject(obstaculo137, 4, 11);
        obstaculo obstaculo138 = new obstaculo();
myWorld.addObject(obstaculo138, 4, 10);
        obstaculo92.setLocation(10, 2);
        obstaculo93.setLocation(9, 4);
        Fantasma fantasma3 = new Fantasma();
myWorld.addObject(fantasma3, 9, 9);
        obstaculo82.setLocation(14, 5);
        obstaculo75.setLocation(5, 6);
        obstaculo90.setLocation(5, 5);
        obstaculo21.setLocation(9, 6);
        bloque obstaculo139 = new bloque();
myWorld.addObject(obstaculo139, 10, 6);
        bloque obstaculo140 = new bloque();
myWorld.addObject(obstaculo140, 10, 4);
        bloque obstaculo141 = new bloque();
myWorld.addObject(obstaculo141, 10, 3);
        obstaculo78.setLocation(8, 9);
        obstaculo6.setLocation(9, 8);
        obstaculo23.setLocation(8, 8);
        obstaculo70.setLocation(6, 9);
        obstaculo120.setLocation(6, 8);
        obstaculo119.setLocation(5, 8);
        obstaculo139.setLocation(9, 10);
        obstaculo obstaculo142 = new obstaculo();
myWorld.addObject(obstaculo142, 13, 3);
        obstaculo obstaculo143 = new obstaculo();
myWorld.addObject(obstaculo143, 13, 2);
        Enemigo enemigo4 = new Enemigo();
myWorld.addObject(enemigo4, 15, 2);
        bloque obstaculo144 = new bloque();
myWorld.addObject(obstaculo144, 10, 6);
        obstaculo110.setLocation(12, 7);
        obstaculo142.setLocation(12, 3);
        obstaculo143.setLocation(12, 2);
        obstaculo112.setLocation(11, 6);
        obstaculo100.setLocation(12, 6);
        bloque obstaculo145 = new bloque();
myWorld.addObject(obstaculo145, 13, 6);
        obstaculo101.setLocation(15, 7);
        bloque obstaculo146 = new bloque();
myWorld.addObject(obstaculo146, 13, 7);
        obstaculo99.setLocation(15, 5);
        obstaculo98.setLocation(15, 4);
        bloque obstaculo147 = new bloque();
myWorld.addObject(obstaculo147, 13, 5);
        bloque obstaculo148 = new bloque();
myWorld.addObject(obstaculo148, 13, 4);
        bloque obstaculo149 = new bloque();
myWorld.addObject(obstaculo149, 13, 4);
        bloque obstaculo150 = new bloque();
myWorld.addObject(obstaculo150, 13, 3);
        obstaculo108.setLocation(12, 9);
        bloque obstaculo151 = new bloque();
myWorld.addObject(obstaculo151, 13, 9);
        obstaculo123.setLocation(14, 10);
        obstaculo111.setLocation(13, 10);
        obstaculo108.setLocation(12, 10);
        obstaculo95.setLocation(12, 9);
        obstaculo96.setLocation(11, 9);
        bloque obstaculo152 = new bloque();
myWorld.addObject(obstaculo152, 12, 8);
        bloque obstaculo153 = new bloque();
myWorld.addObject(obstaculo153, 11, 8);
        meta.setLocation(11, 3);
        obstaculo110.setLocation(9, 2);
        meta.setLocation(12, 7);
        obstaculo111.setLocation(14, 4);
        obstaculo obstaculo154 = new obstaculo();
myWorld.addObject(obstaculo154, 7, 3);
        obstaculo obstaculo155 = new obstaculo();
myWorld.addObject(obstaculo155, 7, 2);
        obstaculo12.setLocation(3, 1);
        obstaculo12.setLocation(3, 1);
        obstaculo12.setLocation(1, 1);
        obstaculo41.setLocation(1, 2);
        obstaculo.setLocation(1, 3);
        obstaculo40.setLocation(1, 4);
        obstaculo2.setLocation(2, 5);
        obstaculo2.setLocation(1, 5);
        obstaculo13.setLocation(1, 6);
        obstaculo3.setLocation(2, 7);
        obstaculo3.setLocation(1, 7);
        obstaculo14.setLocation(1, 8);
        obstaculo4.setLocation(1, 9);
        obstaculo45.setLocation(1, 10);
        obstaculo46.setLocation(1, 11);
        bloque obstaculo156 = new bloque();
        myWorld.addObject(obstaculo156, 1, 12);
        bloque obstaculo157 = new bloque();
        myWorld.addObject(obstaculo157, 2, 12);
        bloque obstaculo158 = new bloque();
        myWorld.addObject(obstaculo158, 2, 1);
        bloque obstaculo159 = new bloque();
        myWorld.addObject(obstaculo159, 3, 1);
        obstaculo31.setLocation(17, 1);
        obstaculo20.setLocation(17, 2);
        obstaculo32.setLocation(17, 3);
        obstaculo34.setLocation(17, 4);
        obstaculo35.setLocation(17, 5);
        obstaculo36.setLocation(17, 6);
        obstaculo37.setLocation(17, 7);
        obstaculo38.setLocation(17, 8);
        obstaculo60.setLocation(17, 9);
        obstaculo59.setLocation(17, 10);
        bloque obstaculo160 = new bloque();
        myWorld.addObject(obstaculo160, 17, 11);
        bloque obstaculo161 = new bloque();
        myWorld.addObject(obstaculo161, 17, 12);
        //jugador.setLocation(2, 2);
        obstaculo22.setLocation(2, 4);
        obstaculo119.setLocation(3, 4);
        obstaculo22.setLocation(2, 3);
        obstaculo119.setLocation(3, 3);
        obstaculo84.setLocation(2, 4);
        obstaculo85.setLocation(4, 3);
        obstaculo85.setLocation(3, 4);
        obstaculo90.setLocation(2, 5);
        obstaculo75.setLocation(3, 5);
        obstaculo86.setLocation(4, 4);
        obstaculo87.setLocation(4, 3);
        obstaculo88.setLocation(4, 2);
        enemigo2.setLocation(5, 2);
        obstaculo89.setLocation(5, 4);
        obstaculo91.setLocation(6, 4);
        obstaculo122.setLocation(5, 3);
        obstaculo122.setLocation(6, 3);
        obstaculo87.setLocation(4, 6);
        obstaculo86.setLocation(5, 5);
        obstaculo122.setLocation(4, 4);
        obstaculo75.setLocation(2, 6);
        obstaculo85.setLocation(2, 8);
        obstaculo122.setLocation(3, 4);
        obstaculo121.setLocation(4, 4);
        obstaculo84.setLocation(3, 5);
        obstaculo22.setLocation(2, 4);
        obstaculo119.setLocation(7, 4);
        obstaculo89.setLocation(7, 5);
        obstaculo44.setLocation(5, 4);
        obstaculo91.setLocation(8, 5);
        obstaculo141.setLocation(6, 4);
        obstaculo140.setLocation(8, 4);
        obstaculo93.setLocation(11, 4);
        obstaculo9.setLocation(9, 4);
        obstaculo144.setLocation(10, 4);
        obstaculo150.setLocation(16, 4);
        obstaculo93.setLocation(11, 2);
        obstaculo149.setLocation(11, 4);
        obstaculo148.setLocation(16, 5);
        obstaculo106.setLocation(13, 2);
        Fantasma fantasma4 = new Fantasma();
        myWorld.addObject(fantasma4, 9, 3);
        bloque obstaculo162 = new bloque();
        myWorld.addObject(obstaculo162, 12, 4);
        bloque obstaculo163 = new bloque();
        myWorld.addObject(obstaculo163, 13, 4);
        obstaculo105.setLocation(16, 6);
        obstaculo111.setLocation(14, 3);
        obstaculo147.setLocation(14, 4);
        bloque obstaculo164 = new bloque();
        myWorld.addObject(obstaculo164, 13, 10);
        obstaculo69.setLocation(4, 8);
        bloque obstaculo165 = new bloque();
        myWorld.addObject(obstaculo165, 7, 8);
        bloque obstaculo166 = new bloque();
        myWorld.addObject(obstaculo166, 5, 8);
        obstaculo69.setLocation(2, 6);
        obstaculo76.setLocation(2, 7);
        obstaculo87.setLocation(3, 6);
        obstaculo75.setLocation(3, 7);
        bloque obstaculo167 = new bloque();
        myWorld.addObject(obstaculo167, 13, 5);
        obstaculo131.setLocation(2, 10);
        fantasma3.setLocation(9, 11);
        Fantasma fantasma5 = new Fantasma();
        myWorld.addObject(fantasma5, 9, 9);
        meta.setLocation(2, 11);
        obstaculo153.setLocation(10, 6);
        fantasma5.setLocation(11, 8);
        Fantasma fantasma6 = new Fantasma();
        myWorld.addObject(fantasma6, 9, 9);
        fantasma6.setLocation(12, 7);
        myWorld.removeObject(fantasma6);
        obstaculo152.setLocation(9, 9);
        fantasma3.setLocation(6, 6);
        obstaculo79.setLocation(9, 11);
        obstaculo127.setLocation(12, 7);
        obstaculo130.setLocation(12, 8);
        obstaculo152.setLocation(10, 9);
        obstaculo139.setLocation(10, 10);
        bloque obstaculo168 = new bloque();
        myWorld.addObject(obstaculo168, 10, 11);
        obstaculo153.setLocation(10, 6);
        obstaculo120.setLocation(6, 4);
        obstaculo141.setLocation(6, 5);
        fantasma3.setLocation(6, 8);
        obstaculo166.setLocation(6, 6);
        obstaculo74.setLocation(4, 5);
        obstaculo71.setLocation(4, 6);
        obstaculo165.setLocation(6, 7);
        obstaculo62.setLocation(5, 6);
        obstaculo64.setLocation(5, 7);
        fantasma3.setLocation(4, 7);
        obstaculo23.setLocation(6, 8);
        obstaculo70.setLocation(4, 9);
        obstaculo70.setLocation(4, 8);
        bloque obstaculo169 = new bloque();
        myWorld.addObject(obstaculo169, 6, 9);
        obstaculo90.setLocation(3, 11);
        meta.setLocation(2, 5);
        obstaculo131.setLocation(2, 11);
        obstaculo obstaculo170 = new obstaculo();
        myWorld.addObject(obstaculo170, 4, 3);
        obstaculo76.setLocation(2, 10);
        Enemigo enemigo5 = new Enemigo();
        myWorld.addObject(enemigo5, 3, 10);
        obstaculo obstaculo171 = new obstaculo();
        myWorld.addObject(obstaculo171, 2, 9);
        obstaculo obstaculo172 = new obstaculo();
        myWorld.addObject(obstaculo172, 3, 8);
        obstaculo obstaculo173 = new obstaculo();
        myWorld.addObject(obstaculo173, 3, 9);
        obstaculo173.setLocation(2, 7);
        llave.setLocation(17, 11);
        obstaculo160.setLocation(19, 11);
        llave.setLocation(16, 11);
        obstaculo160.setLocation(17, 11);
        obstaculo101.setLocation(16, 7);
        obstaculo97.setLocation(16, 8);
        obstaculo103.setLocation(16, 9);
        obstaculo obstaculo174 = new obstaculo();
        myWorld.addObject(obstaculo174, 15, 9);
        obstaculo obstaculo175 = new obstaculo();
        myWorld.addObject(obstaculo175, 15, 10);
        obstaculo obstaculo176 = new obstaculo();
        myWorld.addObject(obstaculo176, 15, 11);
        obstaculo obstaculo177 = new obstaculo();
        myWorld.addObject(obstaculo177, 16, 10);
        obstaculo177.setLocation(15, 7);
        Enemigo enemigo6 = new Enemigo();
        myWorld.addObject(enemigo6, 16, 10);
    }
}
